boostcampwm2023/web18_Dandi

- backend/.gitignore
- backend/package-lock.json
- backend/package.json
- backend/src/app.module.ts
- backend/src/auth/auth.controller.ts
- backend/src/auth/auth.module.ts
- backend/src/auth/auth.repository.ts
- backend/src/auth/auth.service.ts
- backend/src/auth/dto/createUserDto.ts
- backend/src/auth/dto/createUserResponseDto.ts
- backend/src/auth/entity/socialType.ts
- backend/src/auth/entity/user.entity.ts
- backend/src/auth/guards/naverAuth.guard.ts
- backend/src/auth/strategy/naverAuth.strategy.ts
- backend/src/auth/utils/user.decorator.ts
- backend/src/configs/typeorm.config.ts
#8 
- naver api와 연동해 사용자 정보를 가져오도록 구현했습니다.
```ts
export const User = createParamDecorator((data: unknown, executionContext: ExecutionContext) => {
const request = executionContext.switchToHttp().getRequest();
return request.user;
});
```
- oauth callback 이외에도 jwt 파싱에서도 사용될 수 있도록 `@User` 데코레이터를 구현했습니다.
- guard를 거쳐 `req`객체에 저장된 user 정보를 바로 반환해주는 기능을 수행합니다.
- `req.user` -> `user`
> [BE] 네이버 소셜 로그인 기능 구현

- .github/workflows/develop-cd.yml
#7 
- 서비스 서버에 PM2 설치
```
yarn global add pm2
```
- entry point인 `/backend/dist/main.js` 를 데몬화하여 모니터링
```
pm2 start main.js
```
- develop-cd script 수정
기존에 프로그램을 중단하지 않고 그냥 실행시키는 `yarn backend run start:prod`에서
프로세스를 중단 후 다시 실행시키는 `pm2 reload main`으로 script 변경
이후 error 없이 잘 동작하는 것을 볼 수 있다.
> [BE] PM2를 이용한 무중단 배포 적용

- frontend/index.html
- frontend/src/components/Common/Button.tsx
- frontend/src/components/Home/Profile.tsx
- frontend/src/pages/Home.tsx
#39
- 홈 페이지의 프로필 섹션 UI 구현
- 홈 페이지 flex 레이아웃 정렬 수정
- 버튼 컴포넌트의 폰트 크기 조정 prop 추가
> [FE] 홈 프로필 섹션 UI 구현

- backend/src/app.module.ts
- backend/src/diary/diary.module.ts
- backend/src/diary/entity/diary.entity.ts
- backend/src/diary/entity/diaryStatus.ts
- backend/src/diary/entity/tag.entity.ts
#11 
- 일기 CRUD API 구현 이전에 ERD와 동일하게 엔티티를 작성했습니다.
- 리액션 같은 경우 일기 CRUD 단계에서는 불필요해보여 작성하지 않았습니다.
> [BE] 일기 엔티티 생성

- backend/src/diaries/diaries.controller.ts
- backend/src/diaries/diaries.repository.ts
- backend/src/diaries/diaries.service.ts
- backend/src/diaries/dto/diary.dto.ts
- backend/src/diaries/entity/diary.entity.ts
#57
- 응답 화면
- reactionCount는 ERD 변경 중으로 이후 구현 예정입니다.
> [BE] 일기 조회 API 구현

- backend/src/app.module.ts
- backend/src/diaries/diaries.module.ts
- backend/src/diaries/diaries.service.ts
- backend/src/reactions/dto/reaction.dto.ts
- backend/src/reactions/entity/reaction.entity.ts
- backend/src/reactions/reactions.controller.ts
- backend/src/reactions/reactions.module.ts
- backend/src/reactions/reactions.repository.ts
- backend/src/reactions/reactions.service.ts
#105 
---
- 일기 반응 API
특정 사용자가 리액션 버튼 혹은 api로 무수한 요청을 보내는 것을 약간이라도 방지하기 위해서 중복 체크 후 리액션을 저장하도록 구현했습니다.
- 리액션 목록 조회
> [BE] 일기 반응 API / 리액션 목록 API 구현

- frontend/.eslintrc.js
- frontend/src/components/Common/DiaryList.tsx
- frontend/src/components/Common/DiaryListItem.tsx
- frontend/src/components/Home/ProfileEdit.tsx
- frontend/src/components/MyDiary/ViewType.tsx
- frontend/src/pages/MyDiary.tsx
- frontend/tsconfig.json
- frontend/vite.config.ts
close #111
- `@types`로 설정되었던 alias를 `@type`으로 변경
- `@types`를 `typescript`가 사용하기 때문에 에러가 발생했던 것으로 추측
> [FE] path alias 자동 설정 오류 해결

- backend/src/diaries/diaries.repository.ts
- backend/src/diaries/diaries.service.ts
- backend/src/diaries/dto/diary.dto.ts
#131 
- 이모지의 수만 반환하는 것이 아닌 해당 이모지에 연관된 일기의 정보를 함께 반환하도록 변경했습니다.
> [BE] emotion 조회 API 요구사항 변경

- frontend/src/components/Home/Grass.tsx
- frontend/src/components/Home/GrassTooltip.tsx
#142
- mood가 undefined인 경우에도 tooltip이 나오던 문제 해결
- 스크롤 시 전체 잔디가 리렌더링 되던 문제 해결
- 기존 방식: 스크롤 이벤트로 스크롤의 위치를 가져와 Tooltip을 렌더링 해주는 함수에 인자로 넘겨주어 툴팁의 위치를 수정
- 변경된 방식: 툴팁에 마우스를 올릴 때 마다 잔디의 위치를 가져와 툴팁의 위치를 변경해주는 방식
> [FE] 잔디 동작 방식 수정

- backend/src/diaries/diaries.service.ts
#129 
- 3줄 이하의 컨텐츠에 대해서는 summary에 본문 내용 자체를 저장하도록 변경했습니다.
> Clova Summary 오류 수정

- backend/src/diaries/diaries.controller.ts
- backend/src/diaries/dto/diary.dto.ts
> [BE] 일기 조회 API 응답 수정

- backend/src/friends/friends.controller.ts
- backend/src/friends/friends.service.ts
#188 
기존에 친구 목록 조회 시 친구목록과 진행 중인 친구 신청 목록을 같이 조회했는데 이 두가지를 분리함.
> [BE] 친구 목록 조회 API 분리

- frontend/src/api/FriendModal.ts
- frontend/src/components/Home/FriendList.tsx
- frontend/src/components/Home/FriendSearchContent.tsx
- frontend/src/components/Home/Profile.tsx
#150 
- 친구목록 조회 API 연동
- 친구목록 검색 API 연동
검색된 친구가 출력되어야 할 부분이 응답값을 확신하지 못해서 현재 주석으로 처리했습니다.
다음 작업인 친구관리 탭을 완성 후 수정하도록 하겠습니다.
FriendList.tsx에서 마운트 시 실행될  useQuery 중 recommendData 를 받아오는  쿼리를 enabled 옵션으로 nickname이 초기 값일 때 동작하지 않도록 하고
```
useEffect(() => {
recommendData.refetch();
}, [nickname]);
```
useEffect를 사용하여 nickname이 변경될 때 마다 refetch를 받아오도록 했습니다.
하지만 제 생각과 다르게 useEffact가 마운트 시 실행되면서 api주소에 nickname의 초기 값인 `""`이 넘어가서 Bad Request가 발생하고 있습니다.
> [FE] 홈 페이지 - 친구목록 탭 API 연동

- backend/src/diaries/diaries.service.ts
- backend/src/tags/dto/tag.dto.ts
- backend/src/tags/tag.repository.ts
- backend/src/tags/tags.controller.ts
- backend/src/tags/tags.module.ts
- backend/src/tags/tags.service.ts
#166 
일기를 작성 & 수정할 때 사용한 tag를 redis에 저장합니다. 저장할 때 key를 사용자 id로 한 dataset에 저장하며 sorted set을 사용하여 tag를 한 번 사용할 때 마다 score를 +1씩 해줍니다.
태그 추천은 input keyword를 포함하고 있는 tag들을 score가 높은 순으로 반환합니다.
> [BE] 키워드 검색 시 추천 태그 조회 API 구현

- backend/src/diaries/diaries.repository.ts
- backend/src/diaries/diaries.service.ts
- backend/src/diaries/dto/diary.dto.ts
#206
---
lastIndex가 null 인 경우에도 마지막 값부터 일기를 조회할 수 있도록 수정했습니다.
> [BE] 특정 사용자의 일기 조회 API 요청 파라미터 수정

- backend/package.json
- backend/src/auth/auth.controller.ts
- backend/src/auth/auth.repository.ts
- backend/src/auth/auth.service.ts
- backend/src/auth/guards/jwtAuth.guard.ts
- backend/src/auth/utils/auth.constant.ts
- yarn.lock
#164
#211 
- access token과 refresh token을 서비스 자체에서 생성하고 관리하도록 변경했습니다.
- access token은 JWT로 사용자 id, nickname을 담고 있고, refresh token은 UUID입니다.
- redis에 access token을 key, refresh token을 value로 하여 만료기간 2주로 설정하여 저장합니다.
- 로그아웃 시에는 cookie가 만료되도록 했습니다.
- 로직에서 사용되는 URL들은 상수파일로 분리했습니다.
> [BE] 토큰 관리 로직 수정 & 로그아웃 API 구현

- backend/src/diaries/diaries.controller.ts
- backend/src/diaries/diaries.repository.ts
- backend/src/diaries/diaries.service.ts
- backend/src/diaries/entity/diary.entity.ts
#217 
---
로컬 환경에서 서버를 구동해 간단한 성능 테스트도 해봤습니다.
저도 모든 옵션을 잘 알지는 못해서 `http_req_duration`만 일단 말씀드리면, 예상과 같이 v3(엘라스틱서치)를 사용한 검색 성능이 다른 요청에 비해 1초 가량 빨랐습니다.
다만, 예상치못하게 v2가 v1보다 빠를 줄 알았는데 v1이 약간 더 성능상 이점이 있는 것 같이 보여서 이건 좀 더 학습해봐야할 것 같습니다.!
> [BE] 검색 API 페이징 처리 | Full Text Index 적용

- frontend/src/api/DiaryList.ts
- frontend/src/api/EmotionStat.ts
- frontend/src/components/Common/DiaryList.tsx
- frontend/src/components/Common/DiaryListItem.tsx
- frontend/src/components/Common/NavBar.tsx
- frontend/src/components/Common/ProfileItem.tsx
- frontend/src/components/Edit/KeywordBox.tsx
- frontend/src/components/Home/EmotionStat.tsx
- frontend/src/components/Home/FriendSearchContent.tsx
- frontend/src/components/Home/Grass.tsx
- frontend/src/components/Home/Profile.tsx
- frontend/src/components/Home/UserSearchContent.tsx
- frontend/src/components/MyDiary/Calendar.tsx
- frontend/src/components/MyDiary/Card.tsx
- frontend/src/components/MyDiary/CarouselContainer.tsx
- frontend/src/components/MyDiary/DayItem.tsx
- frontend/src/components/MyDiary/MonthContainer.tsx
- frontend/src/components/MyDiary/WeekContainer.tsx
- frontend/src/pages/Feed.tsx
- frontend/src/pages/Home.tsx
- frontend/src/pages/MyDiary.tsx
- frontend/src/types/components/Common/DiaryList.ts
- frontend/src/types/components/Home/Profile.ts
- frontend/src/util/apiPath.ts
- frontend/src/util/constants.ts
- frontend/src/util/funcs.ts
#157, #158, #184
- 내가 작성한 일기 API 연동 마무리
- useInfiniteQuery를 활용한 API 연동
- my-diary 페이지 로직 수정
- 뷰타입 클릭 시 각 뷰타입에 맞는 API 요청하도록 WeekContainer와 MonthContainer 컴포넌트 분리
- 감정 통계 API 연동
- Week undefined 에러 해결
- Card 컴포넌트 클릭 시 일기 디테일로 이동 추가
-----
하다 보니 PR 하나에 담긴 작업의 양이 너무 많네요 🥹 다음 PR은 더 잘게 쪼개보겠습니다!!
> [FE] 내가 작성한 일기 API 연동 마무리 & 로직 수정, 감정 통계 API 연동

- frontend/src/api/FriendModal.ts
- frontend/src/components/Home/FriendModalItem.tsx
- frontend/src/components/Home/ProfileEdit.tsx
#240 
- 프로필 변경 시 홈페이지의 프로필 데이터를 새로 받아오도록 수정
- 친구관련 요청 시 친구관리에 출력할 데이터를 새로 받아오도록 수정
> [FE] 친구 관리 요청을 보낸 후에 리렌더링이 되지 않는 문제 수정

- frontend/src/components/MyDiary/Calendar.tsx
- frontend/src/components/MyDiary/KeywordSearch.tsx
- frontend/src/util/constants.ts
#226, #152
- 키워드 검색 & 추천 키워드 검색
- 제목 + 내용 검색
- 검색 API 연동 완료
- 키워드 추천, 키워드 기반 검색, 제목 + 내용 (Elastic Search) 기반 검색 API
- 피드 API 연동 중
- 500 에러 나서 백엔드 분들께 여쭤본 상황입니다! 고쳐주시면 이어서 마저 연동하겠습니다!
- 검색 디바운싱 적용
- useEffect, setTimeout 활용하여 디바운싱 적용
> [FE] 검색 API 연동 완료, 피드 API 연동 중

- backend/src/users/dto/user.dto.ts
- backend/src/users/entity/user.entity.ts
- backend/src/users/users.controller.ts
- backend/src/users/users.repository.ts
- backend/src/users/users.service.ts
#234 
#254
---
- 잘 동작하는 것 같습니당....
> [BE] 사용자 정보 조회 응답 수정 | lazy loading 삭제

- backend/src/users/users.service.ts
#254
--- 
- ~~확인한줄 알았는데, 하나 놓쳤네요;; 죄송합니다...~~
- 확인한줄 알았는데,두개 놓쳤네요;; 죄송합니다...
> [BE] 친구신청 상태와 관계없이 친구를 카운트하는 문제 수정

- frontend/src/components/Home/EmotionStat.tsx
- frontend/src/globals.css
- frontend/src/util/constants.ts
- frontend/src/util/funcs.ts
#157
- 기간 변경 시 감정 통계 API 재요청되도록 queryKey 수정
- 통계 시작 날짜 => 통계 종료 날짜보다 후인 날짜 선택 못하도록 max 값 설정
- 통계 종료 날짜 => 통계 시작 날짜보다 전인 날짜 선택 못하도록 min 값 설정, 당일보다 후인 날짜 선택 못하도록 max 값 설정
> [FE] 감정 통계 API 재설정 & 통계 기간 input min, max 설정

- backend/src/diaries/diaries.repository.ts
- backend/src/friends/friends.repository.ts
- backend/src/reactions/reactions.controller.ts
- backend/src/reactions/reactions.repository.ts
- backend/src/reactions/reactions.service.ts
#227 
- friends repository에서는 고칠만한 함수가 하난데 이것도 service의 두 곳에서 사용되고 있어서 dto type으로 반환하려면 분리해야하더라구요...? 고민하다가 일단 select에 필드만 특정했습니다. 좋은 의견 있으시면 말씀해주십셔 😊
- reactions module 쿼리 개선
- diaries repository에 하나 빠진게 있어서 수정했습니다.
> [BE] friends, reactions module 쿼리 개선

- backend/src/auth/auth.controller.ts
- backend/src/auth/auth.service.ts
#265 
jwt를 발급할 때 `access key`를 부여하여 이걸로 refresh token을 redis에 저장.
이렇게 함으로써 jwt의 string값이 변경되어도 바뀌지 않는 `access key`가 있어서 refresh token을 찾을 수 있음!!
> [BE] access token 갱신 에러 해결

- backend/src/diaries/diaries.controller.ts
- backend/src/diaries/diaries.repository.ts
- backend/src/diaries/diaries.service.ts
#266 
- 태그로 일기 조회 시 반환값 에러 수정
- diaries module의 `user`, `author` 변수명 통일
> [BE] 태그로 일기 조회 시 반환값 에러 수정

- backend/src/diaries/diaries.controller.ts
- backend/src/diaries/diaries.service.ts
#282 
친구 목록이 없는 경우 `where('diary.author IN (:...idList)', { idList })` 부분에서 idList가 없어서 에러가 나는 것 같아 친구 목록이 없는 경우 빈 배열을 리턴하도록 했습니다.
> [BE] 친구 없는 사용자가 피드 조회 시 발생하는 에러 해결

- frontend/src/pages/Feed.tsx
- frontend/src/pages/Home.tsx
- frontend/src/pages/MyDiary.tsx
#159
https://github.com/boostcampwm2023/web18_Dandi/assets/97578425/2deae13f-3d67-4b05-b2b6-692ee7c8fc39
- intersectionObserver를 적용하여 reflow 없이 요소가 뷰포트 내에 들어왔는지 확인, 들어왔을 경우 다음 데이터 가져옴
> [FE] 무한스크롤 IntersectionObserver 적용

- frontend/package.json
- frontend/src/api/EmotionStat.ts
- frontend/src/api/fetchInterceptor.ts
- frontend/src/components/Home/EmotionStat.tsx
- frontend/src/components/Home/FriendModalItem.tsx
- frontend/src/components/MyDiary/Card.tsx
- frontend/src/components/MyDiary/CarouselContainer.tsx
- frontend/src/globals.css
- yarn.lock
#264, #286, #287, #288
https://github.com/boostcampwm2023/web18_Dandi/assets/97578425/45e3fe42-7518-4c97-b55e-ecc35467ff1d
- Swiper.js 활용하여 캐러셀에 카드 애니메이션 적용
- fetch Interceptor 조건문 수정
- refreshResponse의 status가 401 혹은 500일 때 재로그인 요청
- 친구 홈에서 감정 통계가 현재 로그인한 유저의 것으로 보이는 문제 해결
- 친구 모달의 프로필 사진이 찌그러지는 문제 해결
> [FE] 내가 작성한 일기 (주) 애니메이션 적용 & 버그 수정

- frontend/index.html
- frontend/src/assets/image/logo.svg
- frontend/src/components/Home/EmotionStat.tsx
#298 
- 로그인 페이지에서 단디 로고에 배경색이 들어간 것을 수정
> [FE] 단디 로고 배경색 변경

- backend/src/diaries/diaries.repository.ts
- backend/src/diaries/diaries.service.ts
- backend/src/diaries/dto/diary.dto.ts
- backend/src/reactions/reactions.repository.ts
- backend/src/reactions/reactions.service.ts
#305 
---
```
input {
redis {
host => 
port => 
password => 
data_type => "channel"
key => "diary.event"
}
}
filter {
json {
source => "message"
target => "diary_data"
}
jdbc_streaming {
jdbc_driver_library => 
jdbc_driver_class => 
jdbc_connection_string => 
jdbc_user => 
jdbc_password => 
statement => "
SELECT
diary.id AS diaryid,
diary.title AS title,
diary.content AS content,
diary.summary AS summary,
diary.thumbnail AS thumbnail,
diary.emotion AS emotion,
diary.mood AS mood,
diary.status AS status,
diary.createdAt AS createdat,
diary.updatedAt AS updatedat,
diary.deletedAt AS deletedAt,
GROUP_CONCAT(tag.name) AS tagnames,
GROUP_CONCAT(CONCAT(reaction.userId, ':', reaction.reaction)) AS reactions,
user.id AS authorid,
user.nickname AS authorname
FROM diary
LEFT JOIN diary_tag ON …
```
> [BE] 엘라스틱서치와 MySQL 데이터 동기화 방식 변경

- backend/src/diaries/diaries.repository.ts
> [BE] 검색 시 일기 ID를 조회할 수 없는 문제 수정

- frontend/src/components/Common/DiaryListItem.tsx
- frontend/src/components/Home/EmotionStat.tsx
- frontend/src/components/Home/Grass.tsx
- frontend/src/components/MyDiary/Card.tsx
- frontend/src/components/MyDiary/MonthContainer.tsx
- frontend/src/components/MyDiary/WeekContainer.tsx
- frontend/src/pages/Detail.tsx
- frontend/src/pages/Edit.tsx
- frontend/src/types/components/Common/DiaryList.ts
#330 
- DiaryListItem에서 ReactionList 데이터에 의존되있던 코드를 제거하고 Props로 받아온 데이터를 사용하는 방식으로 변경하였습니다.
- 잔디와 감정통계 데이터를 받아오는 쿼리의 상태를 Fresh로 변경하여 다시 마운트될 때 캐싱된 값을 사용하고  일기 저장, 수정, 삭제
되었을 때  해당 쿼리를 무효화해 다시 데이터를 받아오는 방식으로 변경하였습니다.
> [FE] Home API 요청 최적화

- frontend/index.html
- frontend/src/App.tsx
- frontend/src/components/Common/DiaryListItem.tsx
- frontend/src/components/Common/Modal.tsx
- frontend/src/components/Detail/DiaryContent.tsx
- frontend/src/components/Home/Profile.tsx
- frontend/src/components/MyDiary/Card.tsx
- frontend/src/pages/Detail.tsx
- frontend/src/pages/Home.tsx
- frontend/src/pages/MyDiary.tsx
- frontend/src/util/ModalProvider.tsx
#347
- Modal div 여러 개 생기는 오류 해결
- 하위 컴포넌트가 아닌 부모 컴포넌트에서 Modal을 한 번만 불러오게 하여 해결
- Modal 켜져있을 시 스크롤이 되지 않되, 스크롤바는 사라지지 않도록 수정
- index.html의 SUIT-Variable.css link에 as="style" 속성 추가
> [FE] Modal div 여러 개 생기는 오류 해결

- frontend/src/pages/Detail.tsx
- frontend/src/pages/Home.tsx
#351
https://github.com/boostcampwm2023/web18_Dandi/assets/97578425/e3d1579a-0c90-40bf-af8a-7770fc0d3f52
- 일기 삭제 시 모달 닫히도록 closeModal 함수 실행
- Home에서 userId가 바뀌었을 때 closeModal 함수 실행
> [FE] 페이지 이동 시 모달이 닫히지 않는 문제 해결

- frontend/src/pages/Feed.tsx
- frontend/src/pages/Home.tsx
- frontend/src/pages/MyDiary.tsx
- frontend/src/util/apiPath.ts
- frontend/src/util/funcs.ts
#355
- 내 일기 로딩
- 피드 페이지 로딩
- 홈 페이지 로딩
- date 시간 처리
> [FE] 데이터 로딩 처리 

- nginx/dandi-blue.conf
- nginx/dandi-green.conf
- nginx/nginx.conf
#358 
- 10MB 파일이 로컬에서는 잘 들어가는 상황이라 네트워크를 확인하니 서버가 아닌 NGINX에서 413 에러를 반환하고 있었습니다.
- 때문에 모든 NGINX 설정 파일에 `client_max_body_size`를 추가했습니다.
- 로컬에서는 테스트가 불가해서 머지 해보고 테스트해야할 것 같습니다...
> [BE] 10MB 파일까지 입력 받을 수 있도록 변경

- frontend/src/components/Detail/DiaryContent.tsx
- frontend/src/util/funcs.ts
#361 
https://github.com/boostcampwm2023/web18_Dandi/assets/97578425/016418b9-11e3-46a7-b656-b57f9be9b491
- API 응답으로 내려오는 date string이 UTC => 로컬 타임존과의 시차 구해서 반영
- myData(사용자가 누른 이모지)가 있을 경우에만 갱신 => 사용자가 누른 이모지가 없을 경우 갱신하지 못함
- myData가 없어도 갱신할 수 있도록 수정
> [FE] 날짜 관련 오류 & 상세페이지에 이모지가 제대로 반영되지 않는 문제 해결

- frontend/package.json
- frontend/src/components/MyDiary/ViewType.tsx
- frontend/src/pages/MyDiary.tsx
- frontend/src/store/useViewTypeStore.ts
- frontend/tsconfig.json
- frontend/vite.config.ts
- yarn.lock
#363
- Zustand 설치
- pages의 MyDiary와 하위 컴포넌트인 ViewType에서 공통으로 사용하는 viewType 상태를 store로 분리
- 아직 라이브러리 사용법에 미숙하여 단순한걸 먼저 적용
- 현재 사용중인 상태들을 한눈에 알아볼 수 있도록 도식화를 해볼 것
> [FE] 상태관리 라이브러리 적용

- frontend/src/components/Edit/Editor.tsx
- frontend/src/components/Edit/Header.tsx
- frontend/src/components/Edit/KeywordBox.tsx
- frontend/src/pages/Edit.tsx
- frontend/src/store/useEditStore.ts
- frontend/src/store/useViewTypeStore.ts
- frontend/src/util/apiPath.ts
#363
- Edit 페이지의 상태들을 useEditStore로 분리
- Editor 컴포넌트의 DiaryEditor의 initialValue가 새로 받아온 content로 바뀌지 않는 문제
- 임시방편으로 useLocation의 state의 값을 바로 받아 오는 것으로 변경
> [FE] Edit 페이지 상태 분리

- frontend/src/components/Edit/Editor.tsx
- frontend/src/components/Edit/Header.tsx
- frontend/src/components/Edit/KeywordBox.tsx
- frontend/src/pages/Detail.tsx
- frontend/src/pages/Edit.tsx
- frontend/src/store/useEditStore.ts
#363
- 기존 useNavigate의 state로 정보를 전달하던 방식에서 store에 정보를 저장하여 전달하는 방식으로 변경
- 이전에 문제였던 DiaryEditor의 initialValue가 새로 받아온 content로 바뀌지 않는 문제 해결
- 이전 방식이 state의 존재 여부로 update인지 create인지 구별하기 때문에 state에 update 요청인지 확인할 수 있도록 type을 전달
> [FE] Edit 페이지 state 전달 방식 수정

- frontend/src/api/fetchInterceptor.ts
- frontend/src/pages/OAuthLogin.tsx
#392
- fetch 도중 401 또는 500 에러가 발생했을 때, localStorage를 clear 해주어 이전 user 정보를 초기화 하여 문제 해결
> [FE] 로컬 스토리지 초기화 오류 해결

- backend/test/reactions/reactions.e2e-spec.ts
#382 
`jwtAuthGuard`를 mocking하는게 더 복잡한 것 같아서 그냥 모든 테스트 데이터를 실제로 생성해서 쓰도록 했습니닷
마지막 e2e입니다 🔥🔥
> [BE] Reactions e2e 테스트
