boostcampwm2023/web18_Dandi

backend/.eslintrc.js, backend/.gitignore, backend/.prettierrc, backend/README.md, backend/nest-cli.json, backend/package-lock.json, backend/package.json, backend/src/app.module.ts, backend/src/main.ts, backend/test/app.e2e-spec.ts, backend/test/jest-e2e.json, backend/tsconfig.build.json, backend/tsconfig.json
#2
- NestJS로 프로젝트 생성
- TypeORM, mysql2 설치
- ESLint, Prettier rule 설정
=> [BE] 개발 환경 설정

frontend/.eslintrc.cjs, frontend/.prettierrc, frontend/README.md, frontend/index.html, frontend/package-lock.json, frontend/package.json, frontend/src/App.tsx, frontend/src/main.tsx, frontend/src/vite-env.d.ts, frontend/tsconfig.json, frontend/tsconfig.node.json, frontend/vite.config.ts
=> [FE] 개발 환경 설정

.github/workflows/backend-ci.yml
=> [BE] CI 스크립트 작성

.github/workflows/develop-cd.yml
=> [BE] 개발용 cd script 작성

backend/.eslintrc.js, frontend/.eslintrc.js
#24
- 각 프로젝트의 .eslintrc.js 파일의 extends 경로 수정
=> [Common] .eslintrc.js 파일 수정

.github/workflows/backend-ci.yml
=> [BE] ci 스크립트 수정

.github/workflows/develop-cd.yml
#7 
workflow_dispatch의 경우 workflow를 수동으로 trigger하기 위한 것으로 현재 필요하지 않고, 내용도 없어서 삭제했습니다.
=> chore: 불필요한 코드 삭제 #7

backend/package.json, backend/src/auth/auth.controller.ts, backend/src/auth/dto/user.dto.ts, backend/src/configs/swagger.config.ts, backend/src/main.ts, yarn.lock
#27 
- 기존 API에 swagger를 적용했습니다.
- 표시 정보는 아래와 같습니다.
- API url/description
- API 파라미터
- 성공 시 반환 값/상태 코드
=> [BE] swagger 적용

.prettierrc, frontend/package.json, frontend/src/App.tsx, frontend/src/components/Common/Alert.tsx, frontend/src/components/Common/DiaryList.tsx, frontend/src/components/Common/DiaryListItem.tsx, frontend/src/components/Common/Modal.tsx, frontend/src/components/Common/ProfileItem.tsx, frontend/src/components/Common/Reaction.tsx, package.json, yarn.lock
#34
- prettier-plugin-tailwindcss를 이용하여 tailwindCSS 속성 순서 정렬
=> [FE] tailwindCSS 플러그인 추가

frontend/src/App.tsx, frontend/src/Router.tsx, frontend/src/components/Common/Alert.tsx, frontend/src/components/Common/Button.tsx, frontend/src/components/Common/DiaryList.tsx, frontend/src/components/Common/DiaryListItem.tsx, frontend/src/components/Common/Modal.tsx, frontend/src/components/Common/NavBar.tsx, frontend/src/components/Common/ProfileItem.tsx, frontend/src/components/Common/Reaction.tsx, frontend/src/components/Home/Profile.tsx, frontend/src/components/Login/LoginForm.tsx, frontend/src/main.tsx, frontend/src/pages/Edit.tsx, frontend/src/pages/Feed.tsx, frontend/src/pages/Home.tsx, frontend/src/pages/Login.tsx, frontend/src/pages/MyDiary.tsx, frontend/tsconfig.json, frontend/vite.config.ts
#45 
- path alias 설정하여 import문 변경
=> [FE] path alias 설정

frontend/src/api/Login.ts, frontend/src/components/Login/LoginForm.tsx, frontend/vite.config.ts
#47
- 백엔드와 로그인 API 연동을 시도하고 있습니다.
- path alias의 경로가 잘못 연결된 부분을 수정했습니다.
=> [FE] 로그인 API 연동 & path alias 수정

frontend/src/api/Login.ts, frontend/tsconfig.json
=> [FE] 로그인 API 연동 

backend/src/auth/auth.controller.ts, backend/src/main.ts
=> [BE] 로그인 성공 시 redirect 되도록 변경

backend/src/auth/auth.service.ts, backend/src/auth/strategy/jwtAuth.strategy.ts, backend/src/users/users.module.ts, backend/src/users/users.repository.ts, backend/src/users/users.service.ts
#64 
filename과 해당 class모두 복수형으로 통일함
=> [BE] file name 복수형으로 통일

backend/src/users/dto/user.dto.ts, backend/src/users/users.controller.ts, backend/src/users/users.repository.ts, backend/src/users/users.service.ts
#58 
입력한 검색어가 포함된 nickname을 가진 모든 user를 배열로 반환합니다.
=> [BE] 닉네임으로 사용자검색 기능

backend/src/app.module.ts, backend/src/friends/dto/friend.dto.ts, backend/src/friends/entity/friend.entity.ts, backend/src/friends/entity/friendStatus.ts, backend/src/friends/friends.controller.ts, backend/src/friends/friends.module.ts, backend/src/friends/friends.repository.ts, backend/src/friends/friends.service.ts, backend/src/users/entity/user.entity.ts
#61 
- Friend Entity M:N관계로 작성
TypeORM 문서에서 [이 부분](https://typeorm.io/many-to-many-relations#many-to-many-relations-with-custom-properties) 참고해서 만들었습니다!
- 친구 신청 기능 구현(예외처리O)
먼가 보여드릴 화면이 없네요;
다음 API 구현한건 이거 merge하고 PR 올릴게요!
=> [BE] Friend Entity 생성 & 친구신청 기능 구현

backend/src/friends/dto/friend.dto.ts, backend/src/friends/entity/friend.entity.ts, backend/src/friends/friends.controller.ts, backend/src/friends/friends.repository.ts, backend/src/friends/friends.service.ts, backend/src/users/entity/user.entity.ts
#83 
- 내가 보낸 친구신청 취소 기능 구현
- 리뷰내용 반영했습니다.
=> [BE] 친구신청 취소

backend/src/diaries/diaries.controller.ts, backend/src/diaries/diaries.repository.ts, backend/src/diaries/diaries.service.ts
=> [BE] 일기 삭제 API 구현

backend/src/diaries/diaries.controller.ts, backend/src/diaries/diaries.repository.ts, backend/src/diaries/entity/diary.entity.ts, backend/src/reactions/entity/reaction.entity.ts
=> [BE] Reaction 엔티티 작성

backend/src/friends/entity/friend.entity.ts, backend/src/friends/friends.controller.ts, backend/src/friends/friends.repository.ts, backend/src/friends/friends.service.ts, backend/src/users/entity/user.entity.ts
#63 
내가 받은 친구신청 수락하는 기능
Friend status를 waiting -> complete으로 변경
=> [BE] 친구신청 수락 기능

frontend/src/components/Home/FriendList.tsx, frontend/src/components/Home/FriendModalItem.tsx, frontend/src/components/Home/FriendRequest.tsx, frontend/src/components/Home/Profile.tsx, frontend/src/components/Home/ProfileEdit.tsx
#101 
- 친구목록 구현 
- 친구요청 목록 구현 
- 내 정보 수정 구현 
https://github.com/boostcampwm2023/web18_Dandi/assets/81965433/e8ea83dc-acbc-4999-a71c-1fe8b580b26d
=> [FE] 홈 - 친구관리 Modal

backend/src/reactions/dto/reaction.dto.ts, backend/src/reactions/reactions.controller.ts, backend/src/reactions/reactions.service.ts
=> [BE] 리액션 삭제 API 구현

.gitignore, frontend/src/components/Home/Grass.tsx, frontend/src/components/Home/GrassTooltip.tsx, frontend/src/components/Home/ProfileEdit.tsx, frontend/src/globals.css, frontend/src/pages/Home.tsx, frontend/tailwind.config.js
#79
- 잔디 UI 구성
- 마우스 hover시 해당 날짜의 정보 툴팁 나오는 기능 구현
- Tailwind에서 동적으로 클래스를 할당할 수 있도록 config 수정
=> [FE] 잔디 UI 구성

backend/src/auth/auth.controller.ts
=> [BE] 로그인 http method 수정

backend/src/diaries/diaries.controller.ts, backend/src/diaries/diaries.repository.ts, backend/src/diaries/diaries.service.ts, backend/src/diaries/dto/diary.dto.ts
=> [BE] 기간 내 일기 emotion 조회 API 작성

frontend/src/components/Common/DiaryList.tsx, frontend/src/components/Common/DiaryListItem.tsx, frontend/src/components/Common/Modal.tsx, frontend/src/components/Common/Reaction.tsx, frontend/src/components/Edit/Editor.tsx, frontend/src/components/Edit/Header.tsx, frontend/src/components/Edit/KeywordBox.tsx, frontend/src/components/Edit/KeywordItem.tsx, frontend/src/components/Home/FriendList.tsx, frontend/src/components/Home/FriendModalItem.tsx, frontend/src/components/Home/Grass.tsx, frontend/src/components/Home/GrassTooltip.tsx, frontend/src/components/Home/Profile.tsx, frontend/src/components/Home/ProfileEdit.tsx, frontend/src/components/Login/LoginForm.tsx, frontend/src/components/MyDiary/KeywordSearch.tsx, frontend/src/util/Grass.ts, frontend/tailwind.config.js
#97
- 렌더링 함수 동작 시 오류가 발생하여 롤백
- tailwind.config.js의 safelist를 간략하게 수정
=> [FE] 잔디 렌더링 관련 함수 롤백

frontend/src/components/Home/ProfileEdit.tsx
- ProfileEdit에서 userId가 사용되지 않아 빌드가 되지않던 문제 수정
=> [FE] ProfileEdit 빌드에러 수정

frontend/src/components/Common/Alert.tsx, frontend/src/components/Diary/ReactionList.tsx, frontend/src/components/Home/Grass.tsx, frontend/src/components/Home/Profile.tsx, frontend/src/globals.css, frontend/tailwind.config.js
#144
- reactionList 모달 안의 박스가 모달 밖으로 튀어나오는 문제 수정
- 잔디 오늘 날짜 없던 오류 수정
- Alert 디자인 수정
- 홈페이지 디자인 수정
=> [FE] 디자인 일부 수정

frontend/src/api/Login.ts, frontend/src/components/Login/LoginForm.tsx, frontend/src/pages/OAuthLogin.tsx, frontend/src/util/apiPath.ts, frontend/src/util/constants.ts
close #168
- 객체의 메소드로 API 주소를 반환받게 함
- 참조오류를 수정함
=> [FE] API 주소 반환하는 객체추가, 참조오류 수정

.github/workflows/ci.yml
=> 프론트엔드 CI 설정 추가

backend/src/main.ts, frontend/src/api/Login.ts
=> [BE] cors error 해결

frontend/src/App.tsx, frontend/src/api/Grass.ts, frontend/src/components/Home/Grass.tsx, frontend/src/util/apiPath.ts
=> [FE] 잔디 API 연동

frontend/src/api/Edit.ts, frontend/src/components/Edit/Editor.tsx, frontend/src/components/Edit/Header.tsx, frontend/src/components/Edit/KeywordBox.tsx, frontend/src/pages/Edit.tsx
#151 
- 일기 작성 API를 연동
- 일기 작성중 입력한 키워드 삭제 구현
=> [FE] 일기 작성 API 연동, 입력한 키워드 삭제 구현

frontend/src/pages/Edit.tsx
#181 
- value.trim()에 비교값을 넣어서 빈 값일 경우 api 요청을 막음
=> [FE] 일기 작성 페이지 - 유효성 검사가 작동하지 않는 문제 수정

frontend/src/api/Profile.ts, frontend/src/components/Home/Profile.tsx, frontend/src/pages/Home.tsx, frontend/src/util/apiPath.ts
#155
- 내 홈
- 친구 홈
- react-router의 useParams를 활용해서 친구 홈일 경우 param에서 userId를 가져옵니다.
- 위에서 가져온 userId가 undefined일 경우, localhost에서 userId를 꺼내옵니다.
```javascript
const params = useParams();
const userId = params.userId ? params.userId : localStorage.getItem('userId');
```
=> [FE] 유저 정보 조회 API 연동

frontend/src/api/Reaction.ts, frontend/src/components/Common/DiaryListItem.tsx, frontend/src/components/Detail/DiaryContent.tsx, frontend/src/components/Diary/ReactionList.tsx, frontend/src/components/MyDiary/Card.tsx, frontend/src/pages/Detail.tsx, frontend/src/util/apiPath.ts
=> [FE] 반응 조회 API 연동

frontend/src/api/FriendModal.ts, frontend/src/components/Home/FriendList.tsx, frontend/src/components/Home/FriendModalItem.tsx, frontend/src/components/Home/FriendRequest.tsx, frontend/src/components/Home/FriendSearchContent.tsx, frontend/src/components/Home/Profile.tsx, frontend/src/components/Home/ReceivedRequest.tsx, frontend/src/components/Home/SendRequest.tsx, frontend/src/components/Home/UserSearchContent.tsx, frontend/src/util/apiPath.ts, frontend/src/util/constants.ts
#150 
- 진행중인 친구 요청목록 API 연동
- 보낸 요청
- 받은 요청
- 사용자 검색
- 친구 요청 보내기
https://github.com/boostcampwm2023/web18_Dandi/assets/81965433/8262e1ee-ae4b-46a3-be72-c3ff0ebde8bf
=> [FE] 친구관리 탭 API 연동  - 진행중인 친구 요청목록, 사용자 검색, 친구요청 보내기

frontend/package.json, frontend/src/components/Detail/DiaryContent.tsx, yarn.lock
#197
- react-html-parser 라이브러리를 사용하여 html 태그가 보이는 문제 수정
=> [FE] 일기 내용에 html 태그가 보이는 문제 수정

frontend/src/components/Home/FriendRequest.tsx, frontend/src/components/Home/ReceivedRequest.tsx, frontend/src/components/Home/SendRequest.tsx
#209 
- 받은 요청과 보낸 요청을 출력하는 컴포넌트가 반대로 되있던 문제 수정
- map을 사용해서 undefined가 반환되는 문제 수정
=> [FE] 친구관리 Modal에서 해당하지 않는 사용자가 출력되는 문제 수정

backend/src/reactions/dto/reaction.dto.ts, backend/src/reactions/reactions.controller.ts, backend/src/reactions/reactions.repository.ts, backend/src/reactions/reactions.service.ts
=> [BE] 리액션 수정 API 구현

backend/src/filter/logger.filter.ts, backend/src/images/images.controller.ts, backend/src/images/images.module.ts, backend/src/users/dto/user.dto.ts, backend/src/users/users.controller.ts, backend/src/users/users.module.ts, backend/src/users/users.service.ts
#201 
---
검증 조건이 수정된 데이터가 존재하지 않을 때만 발생하도록 구현했습니다.
=> [BE] 프로필 수정 API 작성

backend/src/friends/friends.controller.ts, backend/src/friends/friends.repository.ts, backend/src/friends/friends.service.ts
=> [BE] 친구 삭제 API 작성

frontend/src/api/FriendModal.ts, frontend/src/components/Home/FriendModalItem.tsx, frontend/src/components/Home/FriendSearchContent.tsx, frontend/src/components/Home/Profile.tsx, frontend/src/components/Home/ProfileEdit.tsx, frontend/src/components/Home/ReceivedRequest.tsx, frontend/src/components/Home/SendRequest.tsx, frontend/src/util/apiPath.ts
#150 
- 보낸 친구요청 취소 API
- 친구 삭제 API
- 친구요청 수락, 거절 API
- 프로필 변경 API
- 프로필 변경 UI 작업
https://github.com/boostcampwm2023/web18_Dandi/assets/81965433/7690fa79-334e-4660-aa53-0104c264a442
=> [FE] 홈 페이지 - 친구관리, 내 정보 수정

backend/src/main.ts, frontend/src/util/apiPath.ts
=> [BE/FE] CORS Origin 변경

frontend/src/api/Reaction.ts, frontend/src/components/Common/DiaryListItem.tsx, frontend/src/components/Detail/DiaryContent.tsx, frontend/src/components/MyDiary/Card.tsx, frontend/src/components/MyDiary/CarouselContainer.tsx, frontend/src/pages/MyDiary.tsx, frontend/src/types/components/Common/ReactionList.ts, frontend/src/util/apiPath.ts
#216
- 반응 추가 API 연동
- 반응 삭제 API 연동
=> [FE] 반응 추가, 삭제 API 연동

frontend/src/components/Common/DiaryListItem.tsx, frontend/src/components/MyDiary/Card.tsx, frontend/src/components/MyDiary/WeekContainer.tsx, frontend/src/pages/MyDiary.tsx, frontend/src/util/apiPath.ts
#236
- MyDiary 코드가 conflict 해결 중 사라져 에러가 발생
- 원래 코드로 되돌려 놓았습니다!
=> [FE] MyDiary 에러 해결

frontend/src/api/DiaryList.ts, frontend/src/api/Feed.ts, frontend/src/api/KeywordSearch.ts, frontend/src/components/Common/DiaryList.tsx, frontend/src/components/Common/DiaryListItem.tsx, frontend/src/components/MyDiary/Calendar.tsx, frontend/src/components/MyDiary/Card.tsx, frontend/src/components/MyDiary/DayItem.tsx, frontend/src/components/MyDiary/KeywordSearch.tsx, frontend/src/components/MyDiary/MonthContainer.tsx, frontend/src/pages/Feed.tsx, frontend/src/pages/Home.tsx, frontend/src/pages/MyDiary.tsx, frontend/src/types/components/MyDiary/MonthContainer.ts, frontend/src/types/pages/MyDiary.ts, frontend/src/util/apiPath.ts
#239
- 친구 홈에서 친구의 일기가 보이도록 수정
- 이미지 없을 시 이미지 태그 뜨지 않도록 수정
- 주, 월 카드 클릭 시 상세 페이지로 이동
=> [FE] 버그 수정 및 기능 추가

backend/src/friends/friends.service.ts, backend/src/users/entity/user.entity.ts, backend/src/users/users.controller.ts
=> [BE] 친구 삭제 오류 수정 | DB 유니크 값 설정

frontend/src/api/FriendModal.ts, frontend/src/components/Edit/Editor.tsx, frontend/src/components/Home/FriendModalItem.tsx, frontend/src/components/Home/Profile.tsx, frontend/src/components/Home/ProfileEdit.tsx, frontend/src/pages/Detail.tsx, frontend/src/pages/Edit.tsx, frontend/src/util/AuthRoutes.tsx, frontend/src/util/PrivateRoutes.tsx
=> [FE] UI 동작 개선

frontend/src/pages/Detail.tsx, frontend/src/pages/MyDiary.tsx
#247
- 일기 삭제 후 내 일기의 일기 불러오는 쿼리를 삭제해줌으로써 데이터를 다시 불러오도록 수정
=> [FE] 일기 삭제 후 삭제된 데이터 불러오던 문제 해결

frontend/src/components/Home/Profile.tsx
=> [FE] 친구 홈의 프로필에서 출력하는 데이터 변경

backend/src/diaries/diaries.controller.ts, backend/src/diaries/diaries.repository.ts, backend/src/diaries/diaries.service.ts, backend/src/diaries/dto/diary.dto.ts, backend/src/diaries/entity/diary.entity.ts
=> [BE] 일기 lazy loading 삭제, Repository 반환값 설정

backend/package.json, backend/src/images/images.repository.ts, backend/src/images/images.service.ts, yarn.lock
#228 
효종님 덕분에 무사히 적용했습니다ㅠㅠ
왼쪽이 리사이징한 이미지인데 겉으로 보기에는 큰 차이 없지만 용량이 확 줄어드네요!
=> [BE] 이미지 리사이징

frontend/src/components/Common/DiaryListItem.tsx, frontend/src/components/Home/FriendList.tsx, frontend/src/components/Home/Profile.tsx, frontend/src/components/MyDiary/Card.tsx, frontend/src/components/MyDiary/CarouselContainer.tsx, frontend/src/components/MyDiary/DayItem.tsx, frontend/src/components/MyDiary/KeywordSearch.tsx, frontend/src/components/MyDiary/WeekContainer.tsx, frontend/src/pages/Feed.tsx, frontend/src/pages/MyDiary.tsx
#263
- 친구 홈에서 새로운 일기 작성하기 없애기
- 월 보기 이모티콘 ➡️ 커서로 변경
- 피드, 일, 주 보기 width 조정
- width 동일하게 통일
- 단, height는 키워드 개수 및 길이
- 키워드, 제목 + 내용 => 본문에 가려짐
=> [FE] 오류 해결

backend/src/diaries/diaries.repository.ts, frontend/src/components/Detail/DiaryContent.tsx, frontend/src/components/Home/Grass.tsx, frontend/src/util/apiPath.ts
#261 #267
- 상세페이지 Cannot read properties of undefined (reading 'map') 에러 해결
- 친구 홈에서도 잔디가 내 잔디로 보이는 문제 해결
=> [공통] 오류 해결

frontend/src/api/Detail.ts, frontend/src/api/DiaryList.ts, frontend/src/api/Edit.ts, frontend/src/api/EmotionStat.ts, frontend/src/api/Feed.ts, frontend/src/api/FriendModal.ts, frontend/src/api/Grass.ts, frontend/src/api/KeywordSearch.ts, frontend/src/api/Login.ts, frontend/src/api/Profile.ts, frontend/src/api/Reaction.ts, frontend/src/api/fetchInterceptor.ts, frontend/src/components/Edit/KeywordBox.tsx
#262 
- refresh token API 연동
- fetch interceptor 구현
- 키워드 입력 안내문구 추가
=> [FE] 엑세스 토큰 재발급 받기, 키워드 입력 안내문구 추가

frontend/src/components/Detail/DiaryContent.tsx, frontend/src/components/Home/EmotionStat.tsx
#278
- emotion 데이터가 없을 때 예외 처리
- detail 인수 네이밍 변경
=> [FE] 오류 수정

frontend/src/components/Edit/Header.tsx, frontend/src/components/Home/FriendList.tsx, frontend/src/components/Home/FriendModalItem.tsx, frontend/src/components/Home/Profile.tsx, frontend/src/pages/Detail.tsx, frontend/src/pages/Edit.tsx
=> [FE] 의도와 다르게 동작하는 오류 수정

backend/src/diaries/diaries.repository.ts, frontend/src/components/Detail/DiaryContent.tsx, frontend/src/components/Home/EmotionCloud.tsx, frontend/src/components/Home/EmotionStat.tsx
#278
- 네이밍 및 변수 수정
- api 날짜 받아오는 코드 일부 수정
=> [공통] 오류 수정

frontend/src/components/Home/FriendRequest.tsx
=> [FE] 돋보기 아이콘 위치수정

frontend/src/components/Common/Modal.tsx, frontend/src/components/Diary/ReactionList.tsx, frontend/src/components/Home/FriendList.tsx, frontend/src/components/Home/FriendRequest.tsx, frontend/src/components/Home/FriendSearchContent.tsx, frontend/src/components/Home/UserSearchContent.tsx, frontend/src/pages/Detail.tsx, frontend/src/pages/Edit.tsx
#312 
- 일기 작성하기
- 일기 삭제하기
- 일기 수정하기 
https://github.com/boostcampwm2023/web18_Dandi/assets/81965433/34470428-1c6a-4752-8c19-9e08950a732b
=> [FE] 일기데이터 변경이 반영되지 않는 오류 수정, 피드백 반영

frontend/src/components/Common/Alert.tsx, frontend/src/components/Common/Button.tsx, frontend/src/components/Common/DiaryListItem.tsx, frontend/src/components/Common/Keyword.tsx, frontend/src/components/Common/Modal.tsx, frontend/src/components/Common/NavBar.tsx, frontend/src/components/Detail/DiaryContent.tsx, frontend/src/components/Edit/Editor.tsx, frontend/src/components/Edit/Header.tsx, frontend/src/components/Edit/KeywordBox.tsx, frontend/src/components/Home/EmotionStat.tsx, frontend/src/components/Home/Grass.tsx, frontend/src/components/Home/Profile.tsx, frontend/src/components/Login/LoginForm.tsx, frontend/src/pages/Detail.tsx, frontend/src/pages/Feed.tsx, frontend/src/pages/Home.tsx
#313 
- 아이폰 12 pro를 기준으로 작성하였습니다.
https://github.com/boostcampwm2023/web18_Dandi/assets/81965433/c2f5c31b-f188-4600-9c0e-c6751a867514
=> [FE] 반응형 웹 디자인 적용 - 홈, 피드, 상세보기, 작성하기

.github/workflows/docker-cd.yml, Dockerfile.front, Dockerfile.was, dandi.conf, docker-compose.yml, frontend/src/util/apiPath.ts
#229 
docker-compose로 https 적용
=> [BE] https 적용

frontend/src/api/fetchInterceptor.ts, frontend/src/components/Common/Loading.tsx, frontend/src/components/Diary/ReactionList.tsx, frontend/src/components/Edit/Header.tsx, frontend/src/components/Home/FriendModalItem.tsx, frontend/src/components/MyDiary/Calendar.tsx, frontend/src/components/MyDiary/CarouselContainer.tsx, frontend/src/components/MyDiary/DayItem.tsx, frontend/src/pages/Detail.tsx, frontend/src/pages/Edit.tsx, frontend/src/pages/Feed.tsx, frontend/src/pages/Home.tsx, frontend/src/pages/MyDiary.tsx, frontend/src/pages/NotFound.tsx, frontend/src/util/constants.ts
#317
https://github.com/boostcampwm2023/web18_Dandi/assets/97578425/52fba6e0-f5d3-44df-8705-150568504b0a
- 내가 작성한 일기 (일) - 너비 조정
- 내가 작성한 일기 (주) - 화살표 없애기
- 내가 작성한 일기 (월) - 달력 크기 줄이기
- 일기 작성 - 이모티콘 선택 z-index 부여
- 데이터 조회 에러 - 404 페이지 이동
- 친구들의 반응 모달 - 높이 조정
- 친구 관리 모달 - FriendModalItem justify-center 삭제
- 디테일 - 수정/삭제 버튼 margin bottom 추가
=> [FE] 반응형 UI 수정

.github/workflows/docker-cd.yml, Dockerfile.front, Dockerfile.was, dandi.conf, docker-compose.yml, frontend/src/api/fetchInterceptor.ts, frontend/src/components/Common/Loading.tsx, frontend/src/components/Diary/ReactionList.tsx, frontend/src/components/Edit/Header.tsx, frontend/src/components/Home/EmotionCloud.tsx, frontend/src/components/Home/EmotionStat.tsx, frontend/src/components/Home/FriendModalItem.tsx, frontend/src/components/MyDiary/Calendar.tsx, frontend/src/components/MyDiary/CarouselContainer.tsx, frontend/src/components/MyDiary/DayItem.tsx, frontend/src/pages/Detail.tsx, frontend/src/pages/Edit.tsx, frontend/src/pages/Feed.tsx, frontend/src/pages/Home.tsx, frontend/src/pages/MyDiary.tsx, frontend/src/pages/NotFound.tsx, frontend/src/util/apiPath.ts, frontend/src/util/constants.ts
#319
- 새로고침 시 emojiCloud의 width를 다시 설정할 수 있도록 수정
- emoji 크기 조정 수식 수정
=> [FE] 감정 통계 UI 수정

frontend/src/App.tsx, frontend/src/components/Home/FriendModalItem.tsx, frontend/src/components/Home/Profile.tsx, frontend/src/components/Home/ProfileEdit.tsx, frontend/src/hooks/useToast.tsx, frontend/src/pages/Detail.tsx, frontend/src/pages/Edit.tsx, frontend/src/util/ToastProvider.tsx
#322 
https://github.com/boostcampwm2023/web18_Dandi/assets/81965433/164732ed-7972-4bb7-9f9e-ebe085288491
=> [FE] Toast 구현

frontend/src/util/apiPath.ts
=> [FE] 잘못된 서버 URL 수정

.github/workflows/docker-cd.yml
=> [BE] github action 스크립트 수정

.github/workflows/docker-cd.yml
#229
배포 스크립트에서 Dockerfile.nginx 경로 수정
=> [BE] Dockerfile.nginx 경로 수정

.github/workflows/docker-cd.yml
#229 
github action script에서 green 버전 제거
=> [BE] github action script에서 green 버전 제거

.github/workflows/docker-cd.yml, backend/src/main.ts, docker/deploy.sh, docker/docker-compose.base.yml, docker/docker-compose.green.yml, nginx/dandi-green.conf, nginx/nginx.conf
#229 
- 깃헙액션 cd script 수정
- backend main.ts 포트 환경변수 사용
- 무중단 배포를 위한 deploy 스크립트 작성
- 최초에 docker 컨테이너 띄우는 docker-compose.base.yml, nginx설정 작성
- 이후 blue/green을 위해 docker-compose 파일과 nginx 설정 파일을 각각 blue 버전, green 버전으로 작성
무려 151번의 테스트 끝에 배포 진짜로 끝났습니다 ㅎ
=> [BE] blue/green 무중단 배포 구축 완료

frontend/index.html, frontend/src/components/Common/Reaction.tsx, frontend/src/components/Home/EmotionStat.tsx, frontend/src/components/MyDiary/KeywordSearch.tsx
#341 
- meta태그에 description을 추가하고 button들에 라벨을 달아서 접근성 개선
=> [FE] Lighthouse 접근성, 권장사항 개선

frontend/src/components/Common/DiaryListItem.tsx, frontend/src/components/Common/Modal.tsx, frontend/src/components/Detail/DiaryContent.tsx, frontend/src/pages/Home.tsx
#345 
- 필요없는 invalidateQueries를 제거하고 useEffact로 렌더링 타이밍 조정
- Modal의 배경에 Toast가 가려지는 문제 수정
=> [FE] 뒤로가기 시 반응이 갱신 안되는 문제 수정 

frontend/src/components/Home/Grass.tsx, frontend/src/components/Home/GrassTooltip.tsx
#349
- window 크기에 따라 잔디의 간격이 너무 벌어지는 문제 수정
=> [FE] 잔디 UI 수정

frontend/src/components/Home/EmotionStat.tsx, frontend/src/util/apiPath.ts
=> [FE] 감정통계 UI 수정

frontend/src/components/Common/DiaryListItem.tsx, frontend/src/components/Detail/DiaryContent.tsx, frontend/src/components/Home/ProfileEdit.tsx, frontend/src/pages/Detail.tsx, frontend/src/pages/Edit.tsx
#357 
- 일기 작성, 삭제 시 목록이 업데이트 되지 않는 문제 수정
- 공감을 남기면 간헐적으로 반영 안되는 현상 수정
=> [FE] 일기 작성, 삭제 시 업데이트 되지 않는 문제 수정

backend/package.json, backend/src/reactions/reactions.service.spec.ts
#364 
어려워서 짧은 reaction부터 해봤어요 ㅋㅋㅋ부족한 부분 있으면 말씀해주십셔~!
=> [BE] reactions service 테스트 코드 작성

backend/src/users/users.service.spec.ts, backend/src/users/users.service.ts
=> [BE] users service 유닛 테스트 작성

backend/src/diaries/diaries.service.ts, backend/src/diaries/utils/clovaRequest.ts
=> [BE] diaries service에서 AI로직 utils로 분리

frontend/package.json, yarn.lock
=> [FE] vite 버전 업데이트

backend/src/diaries/diaries.service.spec.ts
#364 
diary service 테스트 코드 작성 완료
800줄이 넘어가는데... 천천히 봐주십셔 😂 반복이 많습니닷
=> [BE] diary service 유닛테스트

frontend/src/components/Common/DiaryListItem.tsx, frontend/src/components/Detail/DiaryContent.tsx, frontend/src/components/Edit/KeywordBox.tsx, frontend/src/components/Home/FriendModalItem.tsx, frontend/src/components/Home/Profile.tsx, frontend/src/components/Home/ProfileEdit.tsx, frontend/src/components/MyDiary/Card.tsx, frontend/src/hooks/useAllowFriendMutation.ts, frontend/src/hooks/useCancelRequestMutation.ts, frontend/src/hooks/useCreateDiaryMutation.ts, frontend/src/hooks/useDeleteDiaryMutation.ts, frontend/src/hooks/useDeleteFriendMutation.ts, frontend/src/hooks/useDeleteReactionMutation.ts, frontend/src/hooks/usePostReactionMutation.ts, frontend/src/hooks/useReactionListQuery.ts, frontend/src/hooks/useRejectFriendMutation.ts, frontend/src/hooks/useRequestFriendMutation.ts, frontend/src/hooks/useUpdateDiaryMutation.ts, frontend/src/hooks/useUpdateProfileMutation.ts, frontend/src/pages/Detail.tsx
#373
- 컴포넌트에서 직접 호출하는 useQuery를 커스텀 훅으로 분리
=> [FE] 컴포넌트에서 직접 호출하는 useMutation을 커스텀 훅으로 분리

.github/workflows/ci.yml, backend/package.json, backend/src/app.module.ts, backend/src/auth/guards/jwtAuth.guard.ts, backend/src/configs/redis.config.ts, backend/src/configs/typeorm.config.ts, backend/test/app.e2e-spec.ts, backend/test/jest-e2e.json, backend/test/js/app.e2e-spec.ts
=> [BE] e2e 테스트 초기 세팅

backend/src/configs/typeorm.config.ts, backend/test/users/testFile.txt, backend/test/users/users.e2e-spec.ts
=> [BE] Users Controller e2e 테스트 작성
